server:
  port: 10082

spring:
  mqtt:
    host: tcp://116.62.7.32:1883
    clientId: xiaowx #客户端的id
    username: amdin
    password: ******
    timeout: 2000
    keepAlive: 20
    topics: ServerId_01 #主题
    qos: 1 #心跳包级别

